### ISSUE TITLE
TypeError: object NoneType can't be used in 'await' expression

### ISSUE THREAD

**Issue by SeolhwaLee** [acheong08/ChatGPT-lite#13]
Hi, I followed the instruction, but got the below error. 
Could you give any tips for resolving it?

```
(chatgpt) seol@seol-H170-Gaming-3:~/PycharmProjects/respective$ python3 chatGPT_lite.py --async_mode
Starting. Please wait...
You: hello
Traceback (most recent call last):
  File "/home/seol/PycharmProjects/respective/chatGPT_lite.py", line 78, in <module>
    main()
  File "/home/seol/PycharmProjects/respective/chatGPT_lite.py", line 72, in main
    asyncio.run(async_main(args))
  File "/home/seol/miniconda3/envs/chatgpt/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/seol/miniconda3/envs/chatgpt/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/seol/PycharmProjects/respective/chatGPT_lite.py", line 20, in async_main
    response = await chat.ask(prompt)
  File "/home/seol/miniconda3/envs/chatgpt/lib/python3.10/site-packages/ChatGPT_lite/ChatGPT.py", line 81, in ask
    await self.get_tokens()
TypeError: object NoneType can't be used in 'await' expression
```

**Comment by SeolhwaLee** [comment]
It happened because I didn't update my session-token when I login again. That's why get_tokens() doesn't answer anything. 
I solved this problem by updating the session-token. I thought the session-token is the same all the time.
