### ISSUE TITLE
socketio.exceptions.ConnectionError: Connection error

### ISSUE THREAD

**Issue by basketbla** [acheong08/ChatGPT-lite#18]
I made a Flask server using this package and it works great when I run it locally. However, I just tried to host it using [render](https://render.com/), and when I try to connect now it's giving me this error:

[2023-01-15 05:16:29,730] ERROR in app: Exception on /createChatbot [GET]
Jan 14 09:16:29 PM  Traceback (most recent call last):
Jan 14 09:16:29 PM    File "/opt/render/project/src/.venv/lib/python3.7/site-packages/flask/app.py", line 2525, in wsgi_app
Jan 14 09:16:29 PM      response = self.full_dispatch_request()
Jan 14 09:16:29 PM    File "/opt/render/project/src/.venv/lib/python3.7/site-packages/flask/app.py", line 1822, in full_dispatch_request
Jan 14 09:16:29 PM      rv = self.handle_user_exception(e)
Jan 14 09:16:29 PM    File "/opt/render/project/src/.venv/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
Jan 14 09:16:29 PM      return cors_after_request(app.make_response(f(*args, **kwargs)))
Jan 14 09:16:29 PM    File "/opt/render/project/src/.venv/lib/python3.7/site-packages/flask/app.py", line 1820, in full_dispatch_request
Jan 14 09:16:29 PM      rv = self.dispatch_request()
Jan 14 09:16:29 PM    File "/opt/render/project/src/.venv/lib/python3.7/site-packages/flask/app.py", line 1796, in dispatch_request
Jan 14 09:16:29 PM      return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
Jan 14 09:16:29 PM    File "/opt/render/project/src/.venv/lib/python3.7/site-packages/asgiref/sync.py", line 240, in __call__
Jan 14 09:16:29 PM      return call_result.result()
Jan 14 09:16:29 PM    File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 428, in result
Jan 14 09:16:29 PM      return self.__get_result()
Jan 14 09:16:29 PM    File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
Jan 14 09:16:29 PM      raise self._exception
Jan 14 09:16:29 PM    File "/opt/render/project/src/.venv/lib/python3.7/site-packages/asgiref/sync.py", line 306, in main_wrap
Jan 14 09:16:29 PM      result = await self.awaitable(*args, **kwargs)
Jan 14 09:16:29 PM    File "/opt/render/project/src/lite-backend/app.py", line 25, in createChatbot
Jan 14 09:16:29 PM      chatbot = Chatbot(config["session_token"])
Jan 14 09:16:29 PM    File "/opt/render/project/src/.venv/lib/python3.7/site-packages/ChatGPT_lite/ChatGPT.py", line 16, in __init__
Jan 14 09:16:29 PM      f'{bypass_node}/?client=python&version=1.0.2&versionCode=102', transports=['websocket', 'polling'])
Jan 14 09:16:29 PM    File "/opt/render/project/src/.venv/lib/python3.7/site-packages/socketio/client.py", line 282, in connect
Jan 14 09:16:29 PM      six.raise_from(exceptions.ConnectionError(exc.args[0]), None)
Jan 14 09:16:29 PM    File "<string>", line 3, in raise_from
Jan 14 09:16:29 PM  socketio.exceptions.ConnectionError: Connection error

I've looked around and I think it may be some kind of socketio versioning issue (based on [this discussion](https://github.com/miguelgrinberg/python-socketio/issues/586)), but I'm really unsure. Based on that discussion, I added 

`python-engineio==3.14.2 
python-socketio[client]==4.6.0`

To my requirements.txt, but I am still getting the same error. Does anyone know the cause for this error?

**Comment by minglinlu** [comment]
get the same problem with you, have  no idea what to do.
`Starting. Please wait...
Traceback (most recent call last):
  File "lite.py", line 75, in <module>
    main()
  File "lite.py", line 69, in main
    asyncio.run(async_main(args))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "lite.py", line 12, in async_main
    chat = Chatbot(args.session_token, args.bypass_node)
  File "/home/guest/.local/lib/python3.8/site-packages/ChatGPT_lite/ChatGPT.py", line 15, in __init__
    self.socket.connect(
  File "/home/guest/.local/lib/python3.8/site-packages/socketio/client.py", line 338, in connect
    raise exceptions.ConnectionError(exc.args[0]) from None
socketio.exceptions.ConnectionError: Connection error`

**Comment by acheong08** [comment]
Official API released. This is no longer necessary

**Comment by acheong08** [comment]
I will update revChatGPT to use the official API today

**Comment by minglinlu** [comment]
> Official API released. This is no longer necessary

what do you mean by saying `This is no longer necessary`?

**Comment by acheong08** [comment]
The point of this was to bypass the need for browsers. You no longer need browsers using the official API nor Pawan's API

**Comment by acheong08** [comment]
The repository will be archived

**Comment by acheong08** [comment]
Will keep this open I suppose
