### ISSUE TITLE
Error [] Exception in Thread

### ISSUE THREAD

**Issue by steeljardas** [acheong08/ChatGPT-lite#4]
Getting the following error, it's showing up while calling the "ask". Prompt use was: write introduction for the following keyword: 'why dogs cant eat chocolate'

```
def ask_callback(data):
            if 'error' in data:
                print(f'Error: {data["error"]}')
                raise Exception(data['error'])
            conversation['parent_id'] = data['messageId']
            conversation['conversation_id'] = data['conversationId']
            # Put the data in the queue
            data_queue.put_nowait(data)
```

The error:
```
Starting. Please wait...
Error: []Exception in thread 
Thread-6 (_handle_eio_message):
Traceback (most recent call last):
  File "C:\Python\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Python\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Python\lib\site-packages\socketio\client.py", line 707, in _handle_eio_message
    self._handle_ack(pkt.namespace, pkt.id, pkt.data)
  File "C:\Python\lib\site-packages\socketio\client.py", line 606, in _handle_ack
    callback(*data)
  File "C:\Python\lib\site-packages\ChatGPT_lite\ChatGPT.py", line 91, in ask_callback
    raise Exception(data['error'])
Exception: []
```

**Comment by steeljardas** [comment]
Figured out the issue. The prompt can't contain " ' " or "\n"

**Comment by acheong08** [comment]
Yup. Server side issue for now. Getting fixed

**Comment by acheong08** [comment]
Fixed
