### ISSUE TITLE
If a prompt contains a '\n' character, an exception is raised.

### ISSUE THREAD

**Issue by FRCassarino** [acheong08/ChatGPT-lite#5]
It seems that newline characters are being improperly handled somewhere.

Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/frcassarino/Library/Python/3.8/lib/python/site-packages/socketio/client.py", line 707, in _handle_eio_message
    self._handle_ack(pkt.namespace, pkt.id, pkt.data)
  File "/Users/frcassarino/Library/Python/3.8/lib/python/site-packages/socketio/client.py", line 606, in _handle_ack
    callback(*data)
  File "/Users/frcassarino/Library/Python/3.8/lib/python/site-packages/ChatGPT_lite/ChatGPT.py", line 91, in ask_callback
    raise Exception(data['error'])
Exception: [[[[[], []]], [[]], [[]], [[[[]], [[]], [[]], [[]], [[]]]]]]

**Comment by acheong08** [comment]
There are bugs with special characters at the moment on the server side. It is getting fixed

**Comment by acheong08** [comment]
Fixed server side
